// This file is generated by scripts/generate-env.mjs from the root .env file.
// Do not edit it directly.
export const environment = {
  googleClientId: "162320412399-519kqsbii5ls83a1gdo9s3mqub6egn0c.apps.googleusercontent.com",
  loginRoute: "/login",
  defaultRoute: "/",
};
