import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');

function parseEnv(path) {
  const raw = readFileSync(path, 'utf8');
  const out = {};
  for (const line of raw.split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) {
      continue;
    }
    const idx = trimmed.indexOf('=');
    if (idx === -1) {
      continue;
    }
    const key = trimmed.slice(0, idx).trim();
    let value = trimmed.slice(idx + 1).trim();
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    out[key] = value;
  }
  return out;
}

const env = parseEnv(resolve(root, '.env'));
const googleClientId = env.GOOGLE_CLIENT_ID || '';
const authApiUrl = env.NG_AUTH_API_URL || '';
const loginRoute = env.NG_AUTH_LOGIN_ROUTE || '/login';
const defaultRoute = env.NG_AUTH_DEFAULT_ROUTE || '/';

const content = `// This file is generated by scripts/generate-env.mjs from the root .env file.
// Do not edit it directly.
export const environment = {
  googleClientId: ${JSON.stringify(googleClientId)},
  authApiUrl: ${JSON.stringify(authApiUrl)},
  loginRoute: ${JSON.stringify(loginRoute)},
  defaultRoute: ${JSON.stringify(defaultRoute)},
};
`;

const outDir = resolve(root, 'projects/demo/src/environments');
mkdirSync(outDir, { recursive: true });
writeFileSync(resolve(outDir, 'environment.ts'), content);
console.log('Generated projects/demo/src/environments/environment.ts from .env');
